# Generated by Django 4.0 on 2021-12-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='comp_id')),
                ('cpu', models.CharField(max_length=80, verbose_name='CPU')),
                ('graphic_card', models.CharField(max_length=80, verbose_name='Graphic Card')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayClass',
            fields=[
                ('disp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='disp_id')),
                ('room_number', models.CharField(max_length=50)),
                ('square', models.IntegerField(verbose_name='Square')),
            ],
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
        migrations.AddField(
            model_name='computer',
            name='disp_id',
            field=models.ForeignKey(db_column='disp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='application.displayclass', verbose_name='Display Class'),
        ),
    ]
